blueprint:
  name: Reolink Camera Alert with Snapshot, Actions & Snooze
  description: >
    Snapshot notification with optional buttons (Open URL / Open Reolink) and a 6h
    Snooze. Uses a single rolling snapshot file to avoid buildup. Requires a
    Person sensor; optional extra sensors (e.g., doorbell "visitor/pressed").
    Lets you select one or more mobile devices to notify. Title is empty by default;
    message defaults to “Person detected at <Camera>”. NVR channel math is automatic (enter 1–32).
  domain: automation
  input:
    person_sensor:
      name: Person sensor (binary_sensor)
      selector:
        entity: { domain: binary_sensor }

    extra_sensors:
      name: Additional event sensors (optional)
      description: Add doorbell visitor/pressed here; leave empty for cameras.
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    camera:
      name: Camera entity
      selector:
        entity: { domain: camera }

    notify_devices:
      name: Phones to notify
      selector:
        device:
          integration: mobile_app
          multiple: true

    custom_title:
      name: Custom notification title (optional)
      description: Leave blank to keep the title empty (default).
      default: ""
      selector: { text: {} }

    custom_message:
      name: Custom notification text (optional)
      description: >
        Use placeholders: {camera_name}, {event}. Leave blank to use the default:
        "Person detected at {camera_name}".
      default: ""
      selector: { text: {} }

    filename_stem:
      name: Snapshot filename stem (no extension)
      default: "camera"
      selector: { text: {} }

    # Notification icon (MDI) for Companion App notifications
    notification_icon_mdi:
      name: Notification icon (mdi)
      description: MDI icon like "mdi:cctv". Clear to use the app default. (optional)
      default: "mdi:cctv"
      selector: { icon: {} }

    # --- Reolink deep-link params ---
    reolink_uid:
      name: Reolink UID
      selector: { text: {} }

    reolink_devname:
      name: Reolink device name
      default: "NVR"
      selector: { text: {} }

    nvr_channel_index:
      name: NVR channel number (1–32)
      description: The channel number as listed on your NVR (use 1 for direct cameras).
      default: 1
      selector:
        number: { min: 1, max: 32, step: 1, mode: box }

    # --- Action buttons (grouped) ---
    enable_reolink_button:
      name: Show "Open Reolink" button (optional)
      default: true
      selector: { boolean: {} }

    enable_open_url_button:
      name: Show "Open URL" button (optional)
      description: Toggle ON to show; then set the URL and label below.
      default: false
      selector: { boolean: {} }

    open_url:
      name: URL to open (for "Open URL" button)
      description: Optional. Ignored if the toggle above is OFF or if left blank.
      default: ""
      selector: { text: {} }

    open_url_title:
      name: "Open URL" button label
      description: Text shown on the Open URL action button.
      default: "Open URL"
      selector: { text: {} }

    # --- Snooze settings ---
    snooze_timer:
      name: Snooze timer helper
      description: Alerts are suppressed while this timer is active.
      selector:
        entity: { domain: timer }

    snooze_duration:
      name: Snooze duration
      default: "06:00:00"
      selector: { text: {} }

    show_snooze_button:
      name: Show Snooze button (optional)
      default: true
      selector: { boolean: {} }

    snooze_label:
      name: Snooze button label (optional)
      description: Leave blank for a safe default ("Snooze").
      default: ""
      selector: { text: {} }

    snooze_icon_mdi:
      name: Snooze button icon (mdi)
      description: e.g., mdi:bell-sleep-outline
      default: "mdi:bell-sleep-outline"
      selector: { icon: {} }

    # Android channel settings
    android_channel:
      name: Android notification channel name
      default: "Security"
      selector: { text: {} }

    android_importance:
      name: Android channel importance
      default: "high"
      selector:
        select:
          options: [max, high, default, low, min]

    queue_max:
      name: Max queued runs
      default: 10
      selector:
        number: { min: 1, max: 50, step: 1, mode: slider }

mode: queued
max: !input queue_max

triggers:
  - id: person
    platform: state
    entity_id: !input person_sensor
    to: "on"

  - id: visitor
    platform: template
    value_template: >-
      {% set ents = expand(extra_sensors_list) %}
      {% if ents | length == 0 %}
        false
      {% else %}
        {{ (ents | selectattr('state','eq','on') | list | length) > 0 }}
      {% endif %}

  - id: snooze
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: SNOOZE_6H

# Map inputs to variables for templating
variables:
  filename_stem_var: !input filename_stem
  reolink_uid: !input reolink_uid
  reolink_devname: !input reolink_devname
  nvr_channel_index_var: !input nvr_channel_index

  snooze_timer_entity: !input snooze_timer
  extra_sensors_list: !input extra_sensors
  snooze_duration_text: !input snooze_duration
  notify_device_ids: !input notify_devices
  android_channel_var: !input android_channel
  android_importance_var: !input android_importance
  camera_entity: !input camera
  custom_title_text: !input custom_title
  custom_message_text: !input custom_message
  notification_icon_mdi_var: !input notification_icon_mdi

  show_snooze_button_var: !input show_snooze_button
  snooze_label_text: !input snooze_label
  snooze_icon_mdi_var: !input snooze_icon_mdi

  enable_reolink_button_var: !input enable_reolink_button
  enable_open_url_button_var: !input enable_open_url_button
  open_url_text: !input open_url
  open_url_title_text: !input open_url_title

  # Computed
  cam_name: "{{ state_attr(camera_entity, 'friendly_name') or camera_entity }}"
  snap_rel: "{{ '/media/local/reolink/' ~ filename_stem_var ~ '_latest.jpg' }}"
  snap_abs: "{{ '/media/reolink/' ~ filename_stem_var ~ '_latest.jpg' }}"
  bust: "{{ (now() | as_timestamp) | int }}"
  notify_ids_list: >-
    {{ notify_device_ids if notify_device_ids is iterable else [notify_device_ids] }}

  # Compute channel bitmask from channel index (1..32)
  channel_mask: "{{ (2 ** (nvr_channel_index_var | int - 1)) | int }}"

conditions: []

actions:
  - choose:
      # --- Snooze button pressed (only accept from selected devices) ---
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.platform == 'event'
                 and trigger.id == 'snooze'
                 and (trigger.event.data.device_id in notify_ids_list) }}
        sequence:
          - service: timer.start
            target:
              entity_id: "{{ snooze_timer_entity }}"
            data:
              duration: "{{ snooze_duration_text }}"
          - repeat:
              for_each: "{{ notify_ids_list }}"
              sequence:
                - service: "{{ 'notify.mobile_app_' ~ (device_attr(repeat.item, 'name') | slugify) }}"
                  data:
                    title: ""
                    message: "{{ 'Notifications paused for ' ~ snooze_duration_text }}"
                    data:
                      channel: "{{ android_channel_var }}"
                      importance: "{{ android_importance_var }}"
                      notification_icon: "{{ notification_icon_mdi_var }}"

      # --- Person or extra sensor event ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.platform in ['state','template'] }}"
        sequence:
          - condition: template
            value_template: "{{ is_state(snooze_timer_entity, 'idle') }}"

          - service: camera.snapshot
            data:
              entity_id: !input camera
              filename: "{{ snap_abs }}"
          - delay: "00:00:01"

          # Per-event variables
          - variables:
              almtype: "{{ 'PEOPLE' if trigger.id == 'person' else 'VISITOR' }}"
              title_final: "{{ custom_title_text | trim }}"
              event_text: "{{ 'Person detected' if trigger.id == 'person' else 'Doorbell pressed' }}"
              msg_default: "{{ 'Person detected at ' ~ cam_name }}"
              msg_final: >-
                {% set base = custom_message_text | trim %}
                {% if base == '' %}
                  {{ msg_default }}
                {% else %}
                  {{ base
                     | replace('{camera_name}', cam_name)
                     | replace('{event}', event_text) }}
                {% endif %}
              # Single-line Reolink intent (for tap + button)
              intent_uri: >-
                intent://scan/#Intent;scheme=reolink;package=com.mcu.reolink;action=android.intent.action.VIEW;S.UID={{ reolink_uid }};S.DEVNAME={{ reolink_devname }};S.ALMTYPE={{ almtype }};S.ALMCHN={{ channel_mask }};S.ALMNAME=Detection;S.ALMTIME={{ now().isoformat() }};end
              # Build actions as a proper list (no nulls)
              actions_list: >-
                {% set items = [] %}
                {% if enable_open_url_button_var and (open_url_text | trim) != '' %}
                  {% set items = items + [ {'action':'URI','title': open_url_title_text,'uri': open_url_text} ] %}
                {% endif %}
                {% if enable_reolink_button_var %}
                  {% set items = items + [ {'action':'URI','title':'Open Reolink','uri': intent_uri} ] %}
                {% endif %}
                {% if show_snooze_button_var %}
                  {% set label = (snooze_label_text | trim) if (snooze_label_text | trim) != '' else 'Snooze' %}
                  {% set items = items + [ {'action':'SNOOZE_6H','title': label,'icon': snooze_icon_mdi_var} ] %}
                {% endif %}
                {{ items }}

          - repeat:
              for_each: "{{ notify_ids_list }}"
              sequence:
                - service: "{{ 'notify.mobile_app_' ~ (device_attr(repeat.item, 'name') | slugify) }}"
                  data:
                    title: "{{ title_final }}"
                    message: "{{ msg_final }}"
                    data:
                      image: "{{ snap_rel }}?v={{ bust }}"
                      channel: "{{ android_channel_var }}"
                      importance: "{{ android_importance_var }}"
                      notification_icon: "{{ notification_icon_mdi_var }}"
                      clickAction: "{{ intent_uri }}"
                      actions: "{{ actions_list }}"
    default: []
